name: Frontend CI/CD
on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - run: npm ci
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: 'https://branubrain-fs-dev-87a12ee7.web.app/'
          channelId: live
          projectId: branubrain-fs
          target: dev
          entryPoint: .